openapi: 3.0.0
info:
  title: Security API
  version: 1.0.0
servers:
  - url: http://localhost:8000
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: []
paths:
  /api/guard/login:
    post:
      summary: Guard Login
      description: Authenticates a guard and returns a token if within checkpoint area.
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: cghf@hn.com
                password:
                  type: string
                  example: 12345678
                latitude:
                  type: number
                  example: 37.7749
                longitude:
                  type: number
                  example: -122.4194
      responses:
        '200':
          description: Login successful
        '401':
          description: Invalid credentials
        '403':
          description: Not in checkpoint area

  /api/guard/checkpoints:
    get:
      summary: Show Checkpoints
      description: Get all checkpoints assigned to the authenticated guard for today.
      responses:
        '200':
          description: List of checkpoints
        '401':
          description: Unauthorized

  /api/guard/checkpoint/clear:
    post:
      summary: Clear Checkpoint
      description: Mark a checkpoint as cleared by a guard, with separate media uploads (base64).
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - checkpoint_id
                - longitude
                - latitude
                - time
              properties:
                checkpoint_id:
                  type: integer
                  example: 1
                latitude:
                  type: number
                  example: 37.7749
                longitude:
                  type: number
                  example: -122.4194
                time:
                  type: string
                  example: '2024-07-01T12:00:00Z'
                image:
                  type: object
                  description: Image file in base64 format
                  properties:
                    type:
                      type: string
                      example: image/jpeg
                    base64:
                      type: string
                      example: /9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAABAAEDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAv/xAAUEAEAAAAAAAAAAAAAAAAAAAAA/8QAFQEBAQAAAAAAAAAAAAAAAAAAAAX/xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oADAMBAAIRAxEAPwCdABmX/9k=
                video:
                  type: object
                  description: Video file in base64 format
                  properties:
                    type:
                      type: string
                      example: video/mp4
                    base64:
                      type: string
                      example: AAAAGGZ0eXBtcDQyAAAAAGlzb...
                audio:
                  type: object
                  description: Audio file in base64 format
                  properties:
                    type:
                      type: string
                      example: audio/mp3
                    base64:
                      type: string
                      example: AAAAGGZ0eXBtcDQyAAAAAGlzb...
      responses:
        '200':
          description: Checkpoint cleared
        '400':
          description: Not within checkpoint area
        '401':
          description: Invalid or expired token
        '404':
          description: Checkpoint not found

  /api/guard/incident:
    post:
      summary: Store Incident
      description: Report an incident with separate media uploads (base64).
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - longitude
                - latitude
                - time
                - type
              properties:
                latitude:
                  type: number
                  example: 12.9716
                longitude:
                  type: number
                  example: 77.5946
                time:
                  type: string
                  example: '2024-07-01T12:00:00Z'
                type:
                  type: string
                  example: audio
                message:
                  type: string
                  example: Test incident
                image:
                  type: object
                  description: Image file in base64 format
                  properties:
                    type:
                      type: string
                      example: image/jpeg
                    base64:
                      type: string
                      example: /9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAABAAEDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAv/xAAUEAEAAAAAAAAAAAAAAAAAAAAA/8QAFQEBAQAAAAAAAAAAAAAAAAAAAAX/xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oADAMBAAIRAxEAPwCdABmX/9k=
                video:
                  type: object
                  description: Video file in base64 format
                  properties:
                    type:
                      type: string
                      example: video/mp4
                    base64:
                      type: string
                      example: AAAAGGZ0eXBtcDQyAAAAAGlzb...
                audio:
                  type: object
                  description: Audio file in base64 format
                  properties:
                    type:
                      type: string
                      example: audio/mp3
                    base64:
                      type: string
                      example: AAAAGGZ0eXBtcDQyAAAAAGlzb...
      responses:
        '201':
          description: Incident reported
        '401':
          description: Unauthorized
        '500':
          description: Failed to store incident

  /api/guard/incidents/show:
    get:
      summary: Show Incidents
      description: Get all incidents for today for the authenticated guard.
      responses:
        '200':
          description: List of incidents
        '401':
          description: Unauthorized
    post:
      summary: Show Incidents by Date
      description: Get all incidents for the authenticated guard for a specific date.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                date:
                  type: string
                  example: '2025-07-09'
      responses:
        '200':
          description: List of incidents for the date
        '401':
          description: Unauthorized

  /api/guard/alert:
    post:
      summary: Store Alert
      description: Create a new alert for the authenticated guard.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                longitude:
                  type: number
                  example: 77.5946
                latitude:
                  type: number
                  example: 12.9716
                time:
                  type: string
                  example: '2024-07-01T12:00:00Z'
                type:
                  type: string
                  example: alert
                message:
                  type: string
                  example: Test alert
      responses:
        '201':
          description: Alert created
        '401':
          description: Unauthorized
        '500':
          description: Failed to create alert

  /api/guard/checkpoints/show:
    post:
      summary: Show Checkpoints by Date
      description: Get all checkpoints for the authenticated guard for a specific date.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                date:
                  type: string
                  example: '2025-07-09'
      responses:
        '200':
          description: List of checkpoints for the date
        '401':
          description: Unauthorized

  /api/guard/logout:
    get:
      summary: Logout
      description: Logout the authenticated guard and revoke tokens.
      responses:
        '200':
          description: Successfully logged out
        '401':
          description: User not authenticated

  /api/guard/profile/update:
    post:
      summary: Update Guard Profile
      description: Update the authenticated guard's profile information. All fields are optional. If changing password, both password and confirm_password must be provided and must match.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: John Doe
                email:
                  type: string
                  example: cghf@hn.com
                phone:
                  type: string
                  example: '03001234567'
                address:
                  type: string
                  example: 123 Main St
                city:
                  type: string
                  example: San Francisco
                state:
                  type: string
                  example: CA
                zip:
                  type: string
                  example: '94105'
                language:
                  type: string
                  example: English
                cnic:
                  type: string
                  example: 12345-6789012-3
                country:
                  type: string
                  example: USA
                password:
                  type: string
                  example: 12345678
                confirm_password:
                  type: string
                  example: 12345678
      responses:
        '200':
          description: Profile updated successfully
        '401':
          description: Unauthorized
        '500':
          description: Failed to update profile
